document
.getElementById("createBtn")
.addEventListener(
    "click",
    function ()
    {

        let generatedCode = "";

        // ======================================
        // PYTHON HEADER
        // ======================================

        generatedCode +=
            "# -*- coding: utf-8 -*-\n\n";

        generatedCode +=
            "import time\n";

        generatedCode +=
            "from sap.sap_login import SAPLogin\n\n";

        generatedCode +=
            "def generate_costcenter():\n";

        generatedCode +=
            "    return '9' + str(int(time.time()))[-5:]\n\n";

        generatedCode +=
            "def generate_name():\n";

        generatedCode +=
            "    return 'AUTO COST CENTER'\n\n";

        generatedCode +=
            "def generate_long_text():\n";

        generatedCode +=
            "    return 'Generated By MC STAP'\n\n";

        generatedCode +=
            "def get_valid_responsible_person():\n";

        generatedCode +=
            "    return 'Biranchi Das'\n\n";

        generatedCode +=
            "def get_valid_profit_center():\n";

        generatedCode +=
            "    return '1030'\n\n";

        const transactionName =
            window.analysisResults[0]
                .transaction
                .toLowerCase();

        generatedCode +=
            "def test_"
            +
            transactionName
            +
            "(sap_session):\n\n";

        generatedCode +=
            "    # LOGIN\n";

        generatedCode +=
            "    login = SAPLogin(sap_session)\n";

        generatedCode +=
            "    login.login()\n\n";

        generatedCode +=
            "    session = sap_session\n\n";

        let discoveredVariables = {};

        // ======================================
        // VARIABLE DISCOVERY
        // ======================================

        window.analysisResults.forEach(
            result =>
            {

                result.actions.forEach(
                    action =>
                    {

                        if (
                            action.action !==
                            "SET_TEXT"
                        )
                        {
                            return;
                        }

                        if (!action.field)
                        {
                            return;
                        }

                        if (
                            action.field.trim() === ""
                        )
                        {
                            return;
                        }

                        const fieldInfo =
                            getFieldMetadata(
                                action.field.trim()
                            );

                        if (fieldInfo)
                        {
                            discoveredVariables[
                                fieldInfo.variable
                            ] = fieldInfo;
                        }

                    }
                );

            }
        );

        generatedCode +=
            "    # TEST DATA\n\n";

        Object.values(
            discoveredVariables
        ).forEach(
            fieldInfo =>
            {

                generatedCode +=
                    "    # "
                    +
                    fieldInfo.description
                    +
                    " ["
                    +
                    fieldInfo.classification
                    +
                    "]\n";

                generatedCode +=
                    "    "
                    +
                    fieldInfo.variable
                    +
                    " = "
                    +
                    fieldInfo.generator
                    +
                    "\n\n";

            }
        );

        // ======================================
        // TRANSACTION GENERATION
        // ======================================

        window.analysisResults.forEach(
            result =>
            {

                generatedCode +=
                    "\n    # Transaction "
                    +
                    result.transaction
                    +
                    "\n\n";

                generatedCode +=
                    '    session.findById("wnd[0]/tbar[0]/okcd").text = "/n'
                    +
                    result.transaction
                    +
                    '"\n';

                generatedCode +=
                    '    session.findById("wnd[0]").sendVKey(0)\n\n';

                result.actions.forEach(
                    action =>
                    {

                        const businessAction =
                            classifyBusinessAction(
                                action
                            );

                        // ======================================
                        // SET_TEXT
                        // ======================================

                        if (
                            businessAction ===
                            "SET_TEXT"
                        )
                        {

                            if (!action.locator)
                            {
                                return;
                            }

                            if (
                                action.locator ===
                                "wnd[0]/tbar[0]/okcd"
                            )
                            {
                                return;
                            }

                            if (
                                !action.field ||
                                action.field.trim() === ""
                            )
                            {
                                return;
                            }

                            const fieldInfo =
                                getFieldMetadata(
                                    action.field.trim()
                                );

                            if (!fieldInfo)
                            {
                                return;
                            }

                            generatedCode +=
                                "    # "
                                +
                                fieldInfo.description
                                +
                                "\n";

                            generatedCode +=
                                '    session.findById("'
                                +
                                action.locator
                                +
                                '").text = '
                                +
                                fieldInfo.variable
                                +
                                '\n\n';

                        }

                        // ======================================
                        // SEND_VKEY
                        // ======================================

                        else if (
                            businessAction ===
                            "SEND_VKEY"
                        )
                        {

                            if (
                                action.sample_value ===
                                "11"
                            )
                            {

                                generatedCode +=
                                    "\n    # SAVE\n";

                                generatedCode +=
                                    '    session.findById("wnd[0]").sendVKey(11)\n';

                            }

                        }

                        // ======================================
                        // PRESS
                        // ======================================

                        else if (
                            businessAction ===
                            "PRESS"
                        )
                        {
                            // ignored
                        }

                    }
                );

                generatedCode +=
                    "\n";

            }
        );

        // ======================================
        // LOGOFF
        // ======================================

        generatedCode +=
            "\n    # LOGOFF\n";

        generatedCode +=
            '    session.findById("wnd[0]/tbar[0]/okcd").text = "/nex"\n';

        generatedCode +=
            '    session.findById("wnd[0]").sendVKey(0)\n';

        document
        .getElementById(
            "generatedScript"
        )
        .innerText =
            generatedCode;

        document
        .getElementById(
            "saveBtn"
        )
        .disabled = false;

    }
);

function classifyBusinessAction(
    action
)
{
    return action.action;
}