document
.getElementById("createBtn")
.addEventListener(
    "click",
    function ()
    {

        let generatedCode = "";

        generatedCode +=
            "# ======================================\n";

        generatedCode +=
            "# Generated By MC STAP\n";

        generatedCode +=
            "# ======================================\n\n";

        let discoveredVariables =
            {};

        // =========================
        // VARIABLE DISCOVERY
        // =========================

        window.analysisResults.forEach(
            result =>
            {

                result.fields.forEach(
                    field =>
                    {

                        let fieldInfo =
                            getFieldMetadata(
                                field.field
                            );

                        if (fieldInfo)
                        {
                            discoveredVariables[
                                fieldInfo.variable
                            ] = fieldInfo;
                        }

                    }
                );

            }
        );

        generatedCode +=
            "# Variables\n\n";

        Object.values(
            discoveredVariables
        ).forEach(
            fieldInfo =>
            {

                generatedCode +=
			    "# "
			    +
			    fieldInfo.description
			    +
			    " ["
			    +
			    fieldInfo.classification
			    +
			    "]\n";

                generatedCode +=
			    fieldInfo.variable
			    +
			    " = "
			    +
			    fieldInfo.generator
			    +
			    "\n\n";

            }
        );

        // =========================
        // TRANSACTION GENERATION
        // =========================

        window.analysisResults.forEach(
            result =>
            {

                generatedCode +=
                    "\n# Transaction "
                    +
                    result.transaction
                    +
                    "\n\n";

                generatedCode +=
                    'START_TRANSACTION("'
                    +
                    result.transaction
                    +
                    '")\n\n';

                result.actions.forEach(
                    action =>
                    {

                        const businessAction =
                            classifyBusinessAction(
                                action
                            );

                        // ------------------
                        // SET_TEXT
                        // ------------------

                        if (
                            businessAction ===
                            "SET_TEXT"
                        )
                        {

                            if (!action.locator)
					{
					    return;
					}

					if (
					    action.locator ===
					    "wnd[0]/tbar[0]/okcd"
					)
					{
					    return;
					}

					if (
					    !action.field ||
					    action.field.trim() === ""
					)
					{
					    return;
					}

					const fieldInfo =
					    getFieldMetadata(
						  action.field
					    );

					if (!fieldInfo)
					{
					    return;
					}

					const variableName =
					    fieldInfo.variable;

                            generatedCode +=
					    'session.findById("'
					    +
					    action.locator
					    +
					    '").text = '
					    +
					    variableName
					    +
					    '\n';

                        }

                        // ------------------
                        // SEND_VKEY
                        // ------------------

                        else if (
                            businessAction ===
                            "SEND_VKEY"
                        )
                        {

                            // Ignored for now
                            // Recorder noise

                        }

                        // ------------------
                        // PRESS
                        // ------------------

                        else if (
                            businessAction ===
                            "PRESS"
                        )
                        {

                            // Ignored for now
                            // Recorder noise

                        }

                    }
                );

                generatedCode += "\n";

            }
        );

        document
        .getElementById(
            "generatedScript"
        )
        .innerText =
            generatedCode;

        document
        .getElementById(
            "saveBtn"
        )
        .disabled = false;

    }
);

function mapFieldToVariable(field)
{

    const mappings =
    {
        "CSKSZ-KOSTL": "COSTCENTER",
        "CSKSZ-KTEXT": "COSTCENTER_NAME",
        "CSKSZ-LTEXT": "LONG_TEXT",
        "CSKSZ-VERAK": "RESPONSIBLE_PERSON",
        "CSKSZ-PRCTR": "PROFIT_CENTER"
    };

    return mappings[field] || field;
}

function classifyBusinessAction(
    action
)
{
    return action.action;
}