document
.getElementById("saveBtn")
.addEventListener(
    "click",
    async function (event)
    {
	event.preventDefault();
        const generatedScript =
            document
            .getElementById(
                "generatedScript"
            )
            .innerText;

        const transaction =
            window.analysisResults[0]
            .transaction;

        const module =
	    document
	    .getElementById(
		  "module"
	    )
	    .value;

        const formData =
            new FormData();

        formData.append(
	    "script_name",
	    document
		  .getElementById(
			"script_name"
		  )
		  .value
	    );

	  formData.append(
	      "module",
	      module
	  );

        formData.append(
            "transaction_code",
            transaction
        );

        formData.append(
            "description",
            "Generated By MC STAP"
        );

        formData.append(
            "generated_script",
            generatedScript
        );

        formData.append(
            "analysis_results",
            JSON.stringify(
                window.analysisResults
            )
        );

        const response =
            await fetch(
                "/script-studio/save",
                {
                    method: "POST",
                    body: formData
                }
            );

        if (
            response.redirected
        )
        {
            window.location.href =
                response.url;

            return;
        }

        alert(
            "Script saved successfully"
        );

    }
);